-- SQLite

CREATE TABLE Tasks (
TASK_ID INTEGER PRIMARY KEY,
TASK_NAME TEXT NOT NULL,
PRIORITY TEXT CHECK( PRIORITY IN ('HIGH', 'MED', 'LOW'))
)

-- DROP TABLE Tasks;

-- INSERT INTO Tasks (TASK_ID, TASK_NAME, PRIORITY)
-- VALUES (NULL, "TASK 1", "HIGH");

-- DELETE FROM Tasks
-- WHERE TASK_ID IS NULL;

-- SELECT * FROM Tasks;

-- SELECT * FROM sqlite_autoindex_Tasks_1